### ISSUE TITLE
Error with plugin "page-numbering": Unexpected token =

### ISSUE THREAD

**Issue by anakinjay** [lwchkg/gitbook-plugin-page-numbering#1]
Trying to use this with gitbook but I'm getting the following error:

info: loading plugin "page-numbering"... ERROR
PluginError: Error with plugin "page-numbering": Unexpected token =

**Comment by lwchkg** [comment]
The module was written with ES6 and unfortunately the gitbook server is using node 5.1.1. (I don't understand why it isn't any even numbered version.)

I'll update the module in a few hours. BTW, you can try the module locally if you can't wait.

**Comment by anakinjay** [comment]
Thanks so much!

**Comment by lwchkg** [comment]
A new version is now uploaded. You may test it now. I'll also create a testing book in the server.

**Comment by lwchkg** [comment]
Failed because of some stupid .gitignore setting. Uploaded another version, and finally compile succeeded.

You may try to rebuild the book. If not okay, please reopen.
